[ndbd default]
# Configuracion por defecto de los nodos de datos
NoOfReplicas=3                # Numero de replicas de los datos
# ServerPort=1187

[ndb_mgmd]
# Nodo de gestion
hostname=<IP0>      # IP del nodo de gestion
datadir=/var/lib/mysql-cluster
NodeId=1

[ndbd]
# Nodo de datos 1
hostname=<IP1>
NodeId=2
datadir=/usr/local/mysql/data

[ndbd]
# Nodo de datos 2
hostname=<IP2>
NodeId=3
datadir=/usr/local/mysql/data

[ndbd]
Nodo de datos 3
hostname=<IP3>
NodeId=4
datadir=/usr/local/mysql/data

[mysqld]
# Nodo SQL (puede estar en la misma maquina que el gestor)
hostname=<IP0>