host    all             postgres        <IP1>/32          trust
host    all             postgres        <IP2>/32          trust
host    all             postgres        <IP3>/32          trust
host    all             postgres        <IP4>/32          trust